HOST: /api/v1/

--- Raspberry Pi Control Panel ---
---
Web-dashboard for Raspberry Pi.
---

--
Commands Resources
You can use API to execute predefined commands.
--
List of available conmands.
GET /commands
< 200
< Content-Type: application/json
{
    "commands": {
        sample: ["status", "restart"]
    }
}
